# Generated by Django 4.2.16 on 2025-02-14 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_turfs_bookings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='games/')),
            ],
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='turf',
        ),
        migrations.DeleteModel(
            name='Turfs',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='date',
            new_name='booking_date',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='time_slot',
            new_name='booking_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='status',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='turf',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_email',
            field=models.EmailField(default='1', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_name',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Bookings',
        ),
        migrations.DeleteModel(
            name='Turf',
        ),
        migrations.AddField(
            model_name='booking',
            name='game',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='app.game'),
            preserve_default=False,
        ),
    ]
